### ISSUE TITLE
Add README for backend API

### ISSUE THREAD

**Issue by tryyang2001** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#115]
Tasks to do:
- [ ] Create a README for auth-service, include information about how to set up, and the expected .env variables, if possible, add API docs as well, tbd by @tlyi / @xingjie99 
- [x] Create a README for collaboration-service, include information about how to set up, and the expected .env variables, if possible, add events docs as well, tbd by @weidak (added in #103) 
- [x] Create a README for matching-service, include information about how to set up, and the expected .env variables, if possible, add API docs as well, tbd by @c0j0s (added in #113)
- [ ] Update README for question-service, include information about how to set up, and the expected .env variables, as well as the API docs, tbd by @tryyang2001 
- [ ] Update README for user-service, include information about how to set up, and the expected .env variables, as well as the API docs, tbd by @tryyang2001 
- [x] Create a README for history-service, include information about how to set up, and the expected .env variables, as well as the API docs, tbd by @tryyang2001 (added in #104 )

**Comment by tryyang2001** [comment]
To prevent double update, take note that the new route pattern is as follow:
```
<HTTP_METHOD> /<NODE_ENV>/<SERVICE_NAME>/api/<YOUR_ROUTE>
```
- if you are writing docs for auth service, one example of the route pattern will be:
```
POST /development/auth/api/validate
```
This pattern will be updated as soon as this [PR ](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/pull/113)is merged to master.

**Comment by weidak** [comment]
^ the above is no longer accurate, is it?

**Comment by tryyang2001** [comment]
Yes, with refer to js latest [update](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/issues/111#issuecomment-1772759245). Now we don't include `NODE_ENV` in our endpoint route, so it should be:
```
<HTTP_METHOD> /<SERVICE_NAME>/api/<ROUTE_NAME>` 
```
For example:
```
GET /user/api/users/:userId
```
